name: Test cross repos

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # We checkout all the repos required to build the Dockerfile 
      # They are cloned under $GITHUB_WORKSPACE
      - name: Check out repo1
        uses: actions/checkout@v2
        with:
          path: repo1
        
      - name: Check read me repo1
        run: ls $GITHUB_WORKSPACE

      - name: Check out repo2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_REPOS }}
          repository: test-organization-token/repo2
          path: repo2
          
      - name: Check read me repo2
        run: cat $GITHUB_WORKSPACE/repo2/README
        
      - name: Publish real to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: test-image
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: docker_files/Dockerfile 
          tag_names: true # we use tags/release by their git name (main branch pused as latest)
          tag_semver: true # we remove the prefix "v" from the git tag
