name: Test cross repos

on: 
  workflow_dispatch:
  push:
    tags:
    - '*'
  pull_request:
    types: ['ready_for_review']

    
#   workflow_dispatch:
#     inputs:
#       tag:
#         type: choice
#         description: 'Add tag latest/tag-name to the docker image'
#         required: true
#         options:
#         - 'main'
#         - 'v1.0.0'
#         default: true

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      #- name: Get tag
      #  id: tag
      #  run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tag
        
      - name: Print tag
        run: echo ${{steps.tag.outputs.tag}}
         
      # We checkout all the repos required to build the Dockerfile 
      # They are cloned under $GITHUB_WORKSPACE
      # $GITHUB_WORKSPACE = /home/runner/work/repo1/repo1
      # repo1 = /home/runner/work/repo1/repo1/repo1
      # repo2 = /home/runner/work/repo1/repo1/repo2
      - name: Check out repo1
        uses: actions/checkout@v2
        with:
          path: repo1
          ref: ${{steps.tag.outputs.tag}}

      - name: Check out repo2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_REPOS }}
          repository: test-organization-token/repo2
          path: repo2          
          ref: ${{steps.tag.outputs.tag}}
        
      - name: Check workspace
        run: ls $GITHUB_WORKSPACE
        
      - name: Check where we are
        run: |
          pwd 
          ls
          cd repo1
          git status
        
      - name: Publish real to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: test-organization-token/test-image
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: repo1/dockerfiles/Dockerfile 
          workdir: /home/runner/work/repo1/repo1
          tag_names: true # we use tags/release by their git name (main branch pused as latest)
          #tag_semver: true # we remove the prefix "v" from the git tag
