name: Test cross repos

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # We checkout all the repos required to build the Dockerfile 
      # They are cloned under $GITHUB_WORKSPACE
      - name: Check out repo1
        uses: actions/checkout@v2
        
      - name: Check read me repo1
        run: cat $GITHUB_WORKSPACE/repo1/README

      - name: Check out repo2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_REPOS }}
          repository: test-organization-token/repo2
          
      - name: Check read me repo2
        run: cat $GITHUB_WORKSPACE/repo2/README
