name: Test cross repos

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # We checkout all the repos required to build the Dockerfile 
      # They are cloned under $GITHUB_WORKSPACE
      # $GITHUB_WORKSPACE = /home/runner/work/repo1/repo1
      # repo1 = /home/runner/work/repo1/repo1/repo1
      # repo2 = /home/runner/work/repo1/repo1/repo2
      - name: Check out repo1
        uses: actions/checkout@v2
        with:
          path: repo1

      - name: Check out repo2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_REPOS }}
          repository: test-organization-token/repo2
          path: repo2
        
      - name: Check workspace
        run: ls $GITHUB_WORKSPACE
        
      - name: Check where we are
        run: pwd && ls
        
      - name: Publish real to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: test-image
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: repo1/dockerfiles/Dockerfile 
          workdir: ${{ GITHUB_WORKSPACE }} # /home/runner/work/repo1/repo1
          tag_names: true # we use tags/release by their git name (main branch pused as latest)
          tag_semver: true # we remove the prefix "v" from the git tag
